spring:
  application:
    name: auth

  config:
    import: file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,email,profile
            redirect-uri: "{baseUrl}/api/v1/auth/login/oauth2/code/{registrationId}"
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user,user:email
            redirect-uri: "{baseUrl}/api/v1/auth/login/oauth2/code/{registrationId}"

app:
  jwt:
    public-key: classpath:keys/public.pem
    private-key: classpath:keys/private.pem
    meta:
      issuer: https://cakeslayer.dev
      expiry: 15m

  kafka:
    topics:
      email-verification-requested:
        name: auth.email-verification-requested
        replicas: 1
        retention: 1h

springdoc:
  api-docs:
    enabled: true
    path: /api-docs

openapi:
  server-url: http://localhost:8080
  contact-email: mainacc1838@gmail.com
  contact-name: v
  version: "1.0"

email-verification:
  token:
    expiry: 24h