spring:
  application:
    name: auth

  config:
    import: file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true

app:
  jwt:
    public-key: classpath:keys/public.pem
    private-key: classpath:keys/private.pem
